basePath: /api
definitions:
  models.Book:
    properties:
      author:
        maxLength: 255
        type: string
      book_attrs:
        $ref: '#/definitions/models.BookAttrs'
      book_status:
        type: integer
      created_at:
        type: string
      id:
        type: string
      title:
        maxLength: 255
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    required:
    - author
    - book_attrs
    - book_status
    - id
    - title
    - user_id
    type: object
  models.BookAttrs:
    properties:
      description:
        type: string
      picture:
        type: string
      rating:
        maximum: 10
        minimum: 1
        type: integer
    type: object
info:
  contact: {}
paths:
  /v1/book:
    delete:
      responses: {}
      security:
      - ApiKeyAuth: []
    post:
      responses: {}
      security:
      - ApiKeyAuth: []
    put:
      responses: {}
      security:
      - ApiKeyAuth: []
  /v1/book/{id}:
    get:
      responses: {}
  /v1/books:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
  /v1/token/new:
    get:
      responses: {}
swagger: "2.0"
